apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: prowlarr-config
  hostPath:
    path: /opt/prowlarr/config
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["pc1"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeName: prowlarr-config
  resources:
    requests:
      storage: 2Gi
